### PR TITLE
complete initial setup npm webpack babel

### PR DESCRIPTION
**Pull request by yunsupj**
@h-sheeva @bubsinthemountains @KDD87 Please review the initial setup for Webpack, babel, npm

### CODE REVIEW

**Comment by h-sheeva** [comment]
@yunsupj - I only see a single src with an index.js folder.  I don't see the files for webpack or package.json?

**Comment by h-sheeva** [comment]
We should add the .env to the .gitignore to avoid accidentally committing tokens.  Other than that, looks great.  If you make that change, feel free to merge afterwards!

**Comment by yunsupj** [comment]
> .env

**Comment by yunsupj** [comment]
The .env will contain params such as PORT, DB_NAME(not need this project, etc, and I created config.js for store personal Token. so .gitignore has config.js instead of add .env

**Pull request merged**
